# Дод. конфіг (задіювати разом з sich.toml або rmc.toml, ставлячи цей другим). Для тестування якихось змін в більш зручному форматі

[game]
# Час лобі до 30 хвилин, а час до рестарту до 5 годин (тримати 2 клієнта не завжди зручно, tbh)
lobbyduration = 18000
round_restart_time = 180000

[rmc]
# Старт без готового на ксено та дебаг БПП
distress_xenos_minimum = 0
dropship_cas_debug = true
dropship_initial_delay_minutes = 0