- type: rank
  id: RMCRankCivilian
  name: Цивільний
  prefix: Цив.
  malePrefix: Міст.
  femalePrefix: Міс.

- type: rank
  id: RMCRankCivilianNurse
  name: Медсестра
  prefix: Медс.

- type: rank
  id: RMCRankCivilianDoctor
  name: Лікар
  prefix: ДМ #ДМ - Доктор Медицини

- type: rank
  id: RMCRankCivilianAssistantProfessor
  name: Assistant Professor
  prefix: Asst. Prof.

- type: rank
  id: RMCRankCivilianAssociateProfessor
  name: Associate Professor
  prefix: Assoc. Prof.

- type: rank
  id: RMCRankCivilianProfessor
  name: Професор
  prefix: Проф.

- type: rank
  id: RMCRankCivilianRegentsProfessor
  name: Regents Professor
  prefix: Regents Prof.

- type: rank
  id: RMCRankCivilianRepresentative
  name: Представник
  prefix: Пред.

- type: rank
  id: RMCRankCivilianOfficer
  name: Офіцер
  prefix: Оф.

- type: rank
  id: RMCRankCivilianSeniorOfficer
  name: Старший офіцер
  prefix: Ст. Оф.
