- type: rank
  id: RMCRankWeYaTrainee
  name: Стажер
  prefix: Стж.
  paygrade: ВеЯД1

- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Молодший керівник
  prefix: Мол.Кер.
  paygrade: ВеЯД2

- type: rank
  id: RMCRankWeYaExecutive
  name: Керівник
  prefix: Кер.
  paygrade: ВеЯД3

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Старший керівник
  prefix: Старш.Кер.
  paygrade: ВеЯД4

- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Спеціаліст з керівних питань
  prefix: Спец-з-Кер.пит.
  paygrade: ВеЯД5

- type: rank
  id: RMCRankWeYaExecutiveSupervisor
  name: Інспектор з керівних питань
  prefix: Інсп-з-Кер.пит.
  paygrade: ВеЯД6

- type: rank
  id: RMCRankWeYaAssistantManager
  name: Помічник менеджера
  prefix: Помін.Мен.
  paygrade: ВеЯД7

- type: rank
  id: RMCRankWeYaDivisionManager
  name: Керівник відділу
  prefix: Кер.Від.
  paygrade: ВеЯД8

- type: rank
  id: RMCRankWeYaChiefExecutive
  name: Головний керівник
  prefix: Гол.Кер.
  paygrade: ВеЯД9

- type: rank
  id: RMCRankWeYaDeputyDirector
  name: Заступник директора
  prefix: Заст. Директора
  paygrade: ВеЯД10

- type: rank
  id: RMCRankWeYaDirector
  name: Директор
  prefix: Директор
  paygrade: ВеЯД11

# Lawyers
- type: rank
  id: RMCRankWeYaLegalSpecialist
  name: Юридичний спеціаліст
  prefix: Юр.Спец.
  paygrade: WYC5

- type: rank
  id: RMCRankWeYaLegalSupervisor
  name: Юридичний інспектор
  prefix: Юр.Інсп.
  paygrade: WYC6

# Pilots
- type: rank
  id: RMCRankWeYaPilotOfficer
  name: Капітан
  prefix: Кап
  paygrade: ВеЯП2
